import { webmanifest } from "@/app/manifest.json/manifest";

// Add support for the manifest.json route
// Safari apparently doesn't support /manifest.webmanifest
// which is automatically generated by Next.js
export async function GET() {
  return Response.json(webmanifest);
}
